### ISSUE TITLE
lecternTrade throws error when it shouldn't(?)

### ISSUE THREAD

**Issue by mr-hespicable** [senseiwells/clientscript#19]
whenever the villager has two trades which both don't have an enchanted book:
<img width="251" alt="Screen Shot 2023-02-16 at 11 55 39 AM" src="https://user-images.githubusercontent.com/85052021/219358473-ee6dd950-c1a8-48b5-9159-f82166a16a65.png">
the script breaks and says this:
![image](https://user-images.githubusercontent.com/85052021/219359257-90a3dd0d-74e3-4612-b09b-4b8aa6eb56a1.png)

**Comment by senseiwells** [comment]
This has been fixed, thanks for the report!
